// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersSubscriptions.Data;

namespace UsersSubscriptions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<bool>("AllowOneTimePrice");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("OneTimePrice");

                    b.Property<int>("Price");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.CourseAppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("AppUserId")
                        .HasMaxLength(64);

                    b.Property<string>("CourseId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseAppUsers");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.CoursePaymentType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("CourseId")
                        .HasMaxLength(64);

                    b.Property<string>("PaymentTypeId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("CoursePaymentTypes");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.Payment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("PayedToId")
                        .HasMaxLength(64);

                    b.Property<string>("PaymentTypeId")
                        .HasMaxLength(64);

                    b.Property<int>("Price");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("PayedToId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.PaymentType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Priority");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.School", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<DateTime>("AllowTestUntil");

                    b.Property<int>("Balance");

                    b.Property<bool>("Enable");

                    b.Property<bool>("IsPayed");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(64);

                    b.Property<DateTime>("PayedMonth");

                    b.Property<int>("Price");

                    b.Property<string>("UrlName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UrlName")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.SchoolTransaction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("Description");

                    b.Property<int>("NewBalance");

                    b.Property<int>("OldBalance");

                    b.Property<int>("Payed");

                    b.Property<DateTime>("PayedDateTime");

                    b.Property<string>("SchoolId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolTransactions");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("AppUserId")
                        .HasMaxLength(64);

                    b.Property<string>("Comment");

                    b.Property<string>("CourseId")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDatetime");

                    b.Property<string>("FullName")
                        .HasMaxLength(50);

                    b.Property<bool>("MonthSubscription");

                    b.Property<string>("PaymentTypeId");

                    b.Property<DateTime>("Period");

                    b.Property<string>("Phone");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CourseId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UsersSubscriptions.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UsersSubscriptions.Models.Course", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.School", "School")
                        .WithMany("Courses")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.CourseAppUser", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser", "AppUser")
                        .WithMany("CourseAppUsers")
                        .HasForeignKey("AppUserId");

                    b.HasOne("UsersSubscriptions.Models.Course", "Course")
                        .WithMany("CourseAppUsers")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.CoursePaymentType", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.Course", "Course")
                        .WithMany("CoursePaymentTypes")
                        .HasForeignKey("CourseId");

                    b.HasOne("UsersSubscriptions.Models.PaymentType", "PaymentType")
                        .WithMany("CoursePaymentTypes")
                        .HasForeignKey("PaymentTypeId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.Payment", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser", "PayedTo")
                        .WithMany("Payments")
                        .HasForeignKey("PayedToId");

                    b.HasOne("UsersSubscriptions.Models.PaymentType", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId");

                    b.HasOne("UsersSubscriptions.Models.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.PaymentType", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.School")
                        .WithMany("PaymentTypes")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.School", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser", "Owner")
                        .WithMany("Schools")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.SchoolTransaction", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.School", "School")
                        .WithMany("SchoolTransactions")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("UsersSubscriptions.Models.Subscription", b =>
                {
                    b.HasOne("UsersSubscriptions.Models.AppUser", "AppUser")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AppUserId");

                    b.HasOne("UsersSubscriptions.Models.Course", "Course")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CourseId");

                    b.HasOne("UsersSubscriptions.Models.PaymentType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PaymentTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
